name = "QuestionnaireFastTransform"
uuid = "cb9b9665-4f93-45e3-aba9-ebb39a45aeb1"
authors = ["Pei-Chun Su <b94401079@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
